language: minimal
services:

before_install:
    - apt-get update && apt-get upgrade
    - apt-get install -y nim


script:
  - git clone "https://github.com/Adeohluwa/gen"
  - cd gen && nimble install
