language: minimal
services:

before_install:
    - sudo apt-get update && sudo apt-get upgrade
    - sudo apt-get install -y nim


script:
  - git clone "https://github.com/Adeohluwa/gen"
  - cd gen && nimble install
