language: minimal
services:
  - docker

before_install:
  - docker pull nimlang/nim:latest
  - docker images
  - docker ps
  - docker run -d nimlang/nim /bin/bash -c "ls"

script:
  - nim c -r src/gen.nim
