services:
  - docker

before_install:
  - docker pull nimlang/latest
  - docker images
  - docker ps
  - docker run -d nimlang/nim /bin/bash -c "ls"

install:
  - docker-compose build --build-arg NIM_VERSION=$NIM_VERSION

script:
  - nim c -r src/gen.nim
