version: '3.7'
services:
  web:
    image: nginx:latest
    build: .
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_DB=dbname:
      POSTGRES_USER=username:
      POSTGRES_PASSWORD=password:
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
